# Generated by Django 2.2.5 on 2019-09-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(null='True', to='eventFinderApp.Category'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
    ]
