# Generated by Django 2.2.5 on 2019-09-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0002_auto_20190910_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(to='eventFinderApp.Category'),
        ),
    ]
