# Generated by Django 2.2 on 2019-09-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0003_auto_20190904_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(default='TBC', max_length=200),
        ),
    ]
