# Generated by Django 2.2 on 2019-09-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0006_auto_20190907_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(to='eventFinderApp.Category'),
        ),
    ]
