# Generated by Django 2.2 on 2019-09-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0007_auto_20190907_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(null='True', to='eventFinderApp.Category'),
        ),
    ]
